language: node_js
node_js:
- "0.12"

sudo: false

before_script:
- npm install -g  balderdashy/sails appdevdesigns/appdev-cli
- cd /tmp
- /home/travis/build/appdevdesigns/opstool-gmaMatrix/test/setup/install.sh
- cd ad-test/node_modules
- mv /home/travis/build/appdevdesigns/opstool-gmaMatrix .
- cd opstool-gmaMatrix
- npm install

script:
- npm test
 
